### ISSUE TITLE
提交任务报错

### ISSUE THREAD

**Issue by yimingtech** [Lipeng522/flink-connector-redis#1]
在flink1.12里面提交任务任务报错啊
ERROR org.apache.flink.client.cli.CliFrontend [] - Fatal error while running command line interface.
java.lang.NoClassDefFoundError: redis/clients/jedis/exceptions/JedisException
at org.apache.flink.connector.redis.sink.RedisDynamicTableSink.getSinkRuntimeProvider(RedisDynamicTableSink.java:35) ~[?:?]
at org.apache.flink.table.planner.plan.nodes.common.CommonPhysicalSink.createSinkTransformation(CommonPhysicalSink.scala:78) ~

**Comment by Lipeng522** [comment]
这个打包的时候是没有打包依赖的，你需要下载个jedis-3.3.0的jar 放在flink 的lib目录下。https://mvnrepository.com/artifact/redis.clients/jedis/3.3.0 这个地址可以下载。

**Comment by zhangzhitian668** [comment]
> 在flink1.12里面提交任务任务报错啊
> ERROR org.apache.flink.client.cli.CliFrontend [] - Fatal error while running command line interface.
> java.lang.NoClassDefFoundError: redis/clients/jedis/exceptions/JedisException
> at org.apache.flink.connector.redis.sink.RedisDynamicTableSink.getSinkRuntimeProvider(RedisDynamicTableSink.java:35) ~[?:?]
> at org.apache.flink.table.planner.plan.nodes.common.CommonPhysicalSink.createSinkTransformation(CommonPhysicalSink.scala:78) ~

我也是这个报错，请问最后解决了吗？

**Comment by Lipeng522** [comment]
> 在flink1.12里面提交任务任务报错啊
> ERROR org.apache.flink.client.cli.CliFrontend [] - Fatal error while running command line interface.
> java.lang.NoClassDefFoundError: redis/clients/jedis/exceptions/JedisException
> at org.apache.flink.connector.redis.sink.RedisDynamicTableSink.getSinkRuntimeProvider(RedisDynamicTableSink.java:35) ~[?:?]
> at org.apache.flink.table.planner.plan.nodes.common.CommonPhysicalSink.createSinkTransformation(CommonPhysicalSink.scala:78) ~



> > 在flink1.12里面提交任务任务报错啊
> > ERROR org.apache.flink.client.cli.CliFrontend [] - Fatal error while running command line interface.
> > java.lang.NoClassDefFoundError: redis/clients/jedis/exceptions/JedisException
> > at org.apache.flink.connector.redis.sink.RedisDynamicTableSink.getSinkRuntimeProvider(RedisDynamicTableSink.java:35) ~[?:?]
> > at org.apache.flink.table.planner.plan.nodes.common.CommonPhysicalSink.createSinkTransformation(CommonPhysicalSink.scala:78) ~
> 
> 我也是这个报错，请问最后解决了吗？

flink的lib中缺少jar包，你把redis-client的jar包放进去，然后重启flink

**Comment by zhangzhitian668** [comment]
> > 在flink1.12里面提交任务任务报错啊
> > ERROR org.apache.flink.client.cli.CliFrontend [] - Fatal error while running command line interface.
> > java.lang.NoClassDefFoundError: redis/clients/jedis/exceptions/JedisException
> > at org.apache.flink.connector.redis.sink.RedisDynamicTableSink.getSinkRuntimeProvider(RedisDynamicTableSink.java:35) ~[?:?]
> > at org.apache.flink.table.planner.plan.nodes.common.CommonPhysicalSink.createSinkTransformation(CommonPhysicalSink.scala:78) ~
> 
> > > 在flink1.12里面提交任务任务报错啊
> > > ERROR org.apache.flink.client.cli.CliFrontend [] - Fatal error while running command line interface.
> > > java.lang.NoClassDefFoundError: redis/clients/jedis/exceptions/JedisException
> > > at org.apache.flink.connector.redis.sink.RedisDynamicTableSink.getSinkRuntimeProvider(RedisDynamicTableSink.java:35) ~[?:?]
> > > at org.apache.flink.table.planner.plan.nodes.common.CommonPhysicalSink.createSinkTransformation(CommonPhysicalSink.scala:78) ~
> > 
> > 
> > 我也是这个报错，请问最后解决了吗？
> 
> flink的lib中缺少jar包，你把redis-client的jar包放进去，然后重启flink

好的，解决了。
https://mvnrepository.com/artifact/redis.clients/jedis/3.3.0

**Comment by zhangzhitian668** [comment]
大佬，你遇到过这个问题吗？
Log Type: jobmanager.err

Log Upload Time: Wed May 12 18:23:45 +0800 2021

Log Length: 558

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/data/yarn/nm/usercache/root/appcache/application_1616490256517_0320/filecache/12/log4j-slf4j-impl-2.12.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/cloudera/parcels/CDH-6.2.1-1.cdh6.2.1.p0.1425774/jars/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]

你知道这个怎么解决吗？我把任务提交到flink on yarn集群，会报这个错。。。

**Comment by zhangzhitian668** [comment]
> > 在flink1.12里面提交任务任务报错啊
> > ERROR org.apache.flink.client.cli.CliFrontend [] - Fatal error while running command line interface.
> > java.lang.NoClassDefFoundError: redis/clients/jedis/exceptions/JedisException
> > at org.apache.flink.connector.redis.sink.RedisDynamicTableSink.getSinkRuntimeProvider(RedisDynamicTableSink.java:35) ~[?:?]
> > at org.apache.flink.table.planner.plan.nodes.common.CommonPhysicalSink.createSinkTransformation(CommonPhysicalSink.scala:78) ~
> 
> > > 在flink1.12里面提交任务任务报错啊
> > > ERROR org.apache.flink.client.cli.CliFrontend [] - Fatal error while running command line interface.
> > > java.lang.NoClassDefFoundError: redis/clients/jedis/exceptions/JedisException
> > > at org.apache.flink.connector.redis.sink.RedisDynamicTableSink.getSinkRuntimeProvider(RedisDynamicTableSink.java:35) ~[?:?]
> > > at org.apache.flink.table.planner.plan.nodes.common.CommonPhysicalSink.createSinkTransformation(CommonPhysicalSink.scala:78) ~
> > 
> > 
> > 我也是这个报错，请问最后解决了吗？
> 
> flink的lib中缺少jar包，你把redis-client的jar包放进去，然后重启flink

大佬，你遇到过这个问题吗？
Log Type: jobmanager.err

Log Upload Time: Wed May 12 18:23:45 +0800 2021

Log Length: 558

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/data/yarn/nm/usercache/root/appcache/application_1616490256517_0320/filecache/12/log4j-slf4j-impl-2.12.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/cloudera/parcels/CDH-6.2.1-1.cdh6.2.1.p0.1425774/jars/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]

你知道这个怎么解决吗？我把任务提交到flink on yarn集群，会报这个错。。。
